### PR TITLE
Version 4.0.5 upgrade and load/save settings fix for non-english locales

### PR DESCRIPTION
**Pull request by CDC86**
I'm sorry but GitHub is unable to compare the files because it cannot handle the line endings. This causes the whole file to be flagged as different.
The underlying problem is that I must fork your repository to be able to create a pull request later. But your repository enforces Unix-style line endings while Vinny and I use Windows-Style line endings. I have spent mor than five hours fighting GitHub without success and have decided that GitHub is a complete waste of time for me. I'll leave it to you to sort out the mess.

### CODE REVIEW

**Comment by JoeAtGitHub** [comment]
Hi! I'm sorry that you wasted so much time for nothing :-(
Please note that only Vinny can merge your code into the "official" plug-in. This repository has been created for users who wanted to download the German translation before it was available in Vinny's plug-in.

**Comment by CDC86** [comment]
> This repository has been created for users who wanted to download the German translation

Sigh. Then the struggle with GitHub was wasted time indeed.
BTW, do you speak German?

I've noticed a couple of things during testing:

The "Show nearest board" button seems to be fixable, but the fix would require localization strings for the location command alias and the decimal point in every data file.

There are a couple of spelling problems in the german data file which cause items not to be recognized, e.g. everything starting with "Große". I have a near complete set of all trophies for testing that were valid when Version 3.5 was current.

The french translation does not work at all. The format of the data file seems to have changed a while ago. OK. not your project :)

**Comment by JoeAtGitHub** [comment]
> BTW, do you speak German?

Ja, zufälliger Weise spreche ich Deutsch. Wir können auch direkt mailen, ich bin unter "joe punkt translation at arcor punkt de" zu erreichen.

> The "Show nearest board" button seems to be fixable

Tja, leider hat Vinny es bisher abgelehnt, den Programmcode zu ändern. Ich wollte gerne alles übersetzen.

> everything starting with "Große"

Das mit "Grosser ..." ist ja der Hammer, im Interface heißt es "Grosser Flügel", und im Programm dann "Großer Flügel". Ist mir nie aufgefallen ...

**Comment by CDC86** [comment]
Bist Du sicher, dass die Adresse stimmt? Arcor sagt, dass es den 
Benutzer nicht gibt.

Am 22.09.2016 um 21:21 schrieb JoeAtGitHub:
(...)

> ich bin unter "joe punkt translation at arcor punkt de" zu erreichen.
> (...)

**Comment by JoeAtGitHub** [comment]
Oh, sorry, mein Fehler! "joe punkt translation**s** at arcor punkt de" muss es heißen!

**Pull request closed without merging**
